// THIRD_PARTY_NOTICES.md: every production JavaScript package the bundle
// (dist/extension.js) may carry, with its licence text — from
// package-lock.json and node_modules/*/package.json + LICENSE. Fails when a
// package's licence isn't one RapidR's policy allows for bundling
// (MIT, ISC, BSD-2-Clause, BSD-3-Clause, Apache-2.0, 0BSD) or its licence
// text is missing.
//
//   node scripts/notices.js [--check]     (--check: fail if the file is stale)
'use strict';

const fs = require('fs');
const path = require('path');

const ext = path.join(__dirname, '..');
const ALLOWED = new Set(['MIT', 'ISC', 'BSD-2-Clause', 'BSD-3-Clause', 'Apache-2.0', '0BSD']);
const OUT = path.join(ext, 'THIRD_PARTY_NOTICES.md');

function fail(msg) {
    console.error(`notices: ${msg}`);
    process.exit(1);
}

function licenceOf(pkg) {
    if (typeof pkg.license === 'string') return pkg.license;
    if (pkg.license && pkg.license.type) return pkg.license.type;
    if (Array.isArray(pkg.licenses)) return pkg.licenses.map((l) => l.type || l).join(' OR ');
    return null;
}

/** "MIT", "(MIT OR Apache-2.0)": allowed when every alternative of an OR, or every part of an AND, is. */
function allowed(expr) {
    const e = expr.replace(/[()]/g, ' ').trim();
    if (/\bOR\b/.test(e)) return e.split(/\bOR\b/).some((x) => allowed(x));
    if (/\bAND\b/.test(e)) return e.split(/\bAND\b/).every((x) => allowed(x));
    return ALLOWED.has(e.trim());
}

function licenceText(dir) {
    const names = fs.readdirSync(dir).filter((f) => /^(licen[sc]e|copying)(\.(md|txt))?$/i.test(f));
    if (names.length === 0) return null;
    return fs.readFileSync(path.join(dir, names[0]), 'utf8').trim();
}

const lock = JSON.parse(fs.readFileSync(path.join(ext, 'package-lock.json'), 'utf8'));
const entries = Object.entries(lock.packages || {})
    .filter(([key, meta]) => key.startsWith('node_modules/') && !meta.dev && !meta.devOptional)
    .map(([key]) => key)
    .sort((a, b) => {
        const name = (k) => k.slice(k.lastIndexOf('node_modules/') + 13);
        return name(a).localeCompare(name(b)) || a.localeCompare(b);
    });
if (entries.length === 0) fail('no production packages in package-lock.json (npm install first)');

const sections = [];
const rows = [];
for (const key of entries) {
    const dir = path.join(ext, key);
    if (!fs.existsSync(path.join(dir, 'package.json'))) fail(`${key}: not installed (npm install first)`);
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
    const licence = licenceOf(pkg);
    if (!licence) fail(`${pkg.name}: no licence in its package.json`);
    if (!allowed(licence)) fail(`${pkg.name} ${pkg.version}: licence "${licence}" isn't allowed (MIT, ISC, BSD, Apache-2.0, 0BSD)`);
    const text = licenceText(dir);
    if (!text) fail(`${pkg.name} ${pkg.version}: no LICENSE file to reproduce`);
    const repo = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository && pkg.repository.url;
    rows.push(`| ${pkg.name} | ${pkg.version} | ${licence} |`);
    sections.push(
        `## ${pkg.name} ${pkg.version}\n\n` +
        `Licence: ${licence}${repo ? `  \nSource: ${repo.replace(/^git\+/, '').replace(/\.git$/, '')}` : ''}\n\n` +
        '```text\n' + text + '\n```\n',
    );
}

const doc =
    '# Third-party notices: RapidR for VS Code\n\n' +
    'The extension (MIT, see LICENSE) bundles these JavaScript packages into `dist/extension.js`. ' +
    'Generated by `scripts/notices.js` from package-lock.json; do not edit by hand.\n\n' +
    'The language server and the debug adapter are part of RapidR itself (`rapidr lsp`, `rapidr dap`), ' +
    'not of this extension: RapidR\'s own notices come with RapidR (`rapidr notices`).\n\n' +
    '| Package | Version | Licence |\n|---|---|---|\n' + rows.join('\n') + '\n\n' +
    sections.join('\n');

if (process.argv.includes('--check')) {
    const now = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (now !== doc) fail('THIRD_PARTY_NOTICES.md is stale: npm run notices');
    console.log(`THIRD_PARTY_NOTICES.md: up to date (${rows.length} packages)`);
} else {
    fs.writeFileSync(OUT, doc);
    console.log(`THIRD_PARTY_NOTICES.md: ${rows.length} packages (${rows.map((r) => r.split('|')[1].trim()).join(', ')})`);
}
