[workspace]
resolver = "2"
members = [
    "crates/rapidr-cli",
    "crates/rapidr-diagnostics",
    "crates/rapidr-ast",
    "crates/rapidr-lexer",
    "crates/rapidr-parser",
    "crates/rapidr-preprocessor",
    "crates/rapidr-runtime-core",
    "crates/rapidr-runtime-web",
    "crates/rapidr-codegen-rust",
    "crates/rapidr-buildserver",
]

[workspace.package]
edition = "2021"
version = "1.0.0"
license = "MIT"

[workspace.dependencies]
rapidr-ast = { path = "crates/rapidr-ast" }
rapidr-diagnostics = { path = "crates/rapidr-diagnostics" }
rapidr-lexer = { path = "crates/rapidr-lexer" }
rapidr-parser = { path = "crates/rapidr-parser" }
rapidr-preprocessor = { path = "crates/rapidr-preprocessor" }
rapidr-runtime-core = { path = "crates/rapidr-runtime-core" }
rapidr-runtime-web = { path = "crates/rapidr-runtime-web" }
rapidr-codegen-rust = { path = "crates/rapidr-codegen-rust" }