import { chromium } from "playwright";
import { readFileSync } from "node:fs";
const b = await chromium.launch(); const page = await b.newPage();
const logs = []; page.on("console", (m) => logs.push(m.text()));
await page.goto("http://localhost:8765/web-ide/index.html");
await page.waitForFunction(() => document.getElementById("status")?.textContent?.includes("ready"));
await page.evaluate((s) => { window.RapidR.state.project.forms[0].code = { handlers: {}, source: s }; window.RapidR.runCommand("run.start"); }, readFileSync(process.argv[2], "utf8"));
await page.waitForTimeout(2500);
const f = page.frames().find((f) => f.url().includes("preview.html"));
const get = (c, p) => f.evaluate(([c, p]) => window.__rapidr_rt.rapidr_get_prop(c, p), [c, p]);
console.log("before close:", await get("LBL", "caption"), await get("FORM", "__shown"));
await f.evaluate(() => document.getElementById("rr-btn").click()); await page.waitForTimeout(800);
console.log("after close:", await get("LBL", "caption"));
console.log("output:", await page.evaluate(() => document.body.innerText.match(/after modal/g)?.length ?? 0));
await b.close();
