[package]
name = "rapidr-vm-host-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rapidr-value = { workspace = true }
rapidr-bytecode = { workspace = true }
rapidr-vm = { workspace = true }
rapidr-runtime-web = { workspace = true }
wasm-bindgen = "0.2"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = ["Window", "Document", "console"]
