[package]
name = "rapidr-webbundle"
version.workspace = true
edition.workspace = true
description = "Build a downloadable static-hostable web bundle (.zip) from a .rrbc + rapidrintr.wasm/js."

[dependencies]
rapidr-rrcss = { workspace = true }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
