//! Network backends — RSocket, RServerSocket, RHTTP.

use std::cell::RefCell;
use std::collections::HashMap;
use std::io::{BufRead, BufReader, Read, Write};
use std::net::{TcpListener, TcpStream};
use std::sync::{Arc, Mutex, mpsc};
use std::time::Duration;

use crate::object::{rp_comp_set, rp_fire_event, rp_fire_event_1, rp_fire_event_2};
use crate::value::{v_int, v_null, v_str, Value};

// ---------------------------------------------------------------------------
// RSocket (TCP client)
// ---------------------------------------------------------------------------

struct SocketState {
    stream: TcpStream,
    reader: BufReader<TcpStream>,
}

thread_local! {
    static SOCKETS: RefCell<HashMap<String, SocketState>> = RefCell::new(HashMap::new());
}

pub fn socket_method(name: &str, method: &str, args: &[Value]) -> Value {
    let name_lower = name.to_lowercase();
    match method {
        "connect" => socket_connect(&name_lower),
        "close" | "disconnect" => socket_close(&name_lower),
        "write" => socket_write(&name_lower, args, false),
        "writeline" => socket_write(&name_lower, args, true),
        "read" => socket_read(&name_lower, args),
        "readline" => socket_readline(&name_lower),
        _ => {
            eprintln!("[WARN] RSocket.{}() not implemented", method);
            v_null()
        }
    }
}

fn socket_connect(name: &str) -> Value {
    let host = crate::object::rp_comp_get(name, "host").to_string_val();
    let port = crate::object::rp_comp_get(name, "port").to_i64() as u16;
    let timeout_ms = crate::object::rp_comp_get(name, "timeout").to_i64().max(1000) as u64;

    let addr = format!("{}:{}", host, port);
    match TcpStream::connect_timeout(
        &addr.parse().unwrap_or_else(|_| {
            format!("127.0.0.1:{}", port).parse().unwrap()
        }),
        Duration::from_millis(timeout_ms),
    ) {
        Ok(stream) => {
            let _ = stream.set_read_timeout(Some(Duration::from_millis(timeout_ms)));
            let _ = stream.set_write_timeout(Some(Duration::from_millis(timeout_ms)));
            let reader = BufReader::new(stream.try_clone().unwrap());
            SOCKETS.with(|s| {
                s.borrow_mut().insert(
                    name.to_string(),
                    SocketState { stream, reader },
                );
            });
            rp_comp_set(name, "connected", v_int(1));
            v_int(1)
        }
        Err(e) => {
            eprintln!("[Socket] Connect error: {}", e);
            rp_comp_set(name, "connected", v_int(0));
            v_int(0)
        }
    }
}

fn socket_close(name: &str) -> Value {
    SOCKETS.with(|s| {
        if let Some(state) = s.borrow_mut().remove(name) {
            let _ = state.stream.shutdown(std::net::Shutdown::Both);
        }
    });
    rp_comp_set(name, "connected", v_int(0));
    v_null()
}

fn socket_write(name: &str, args: &[Value], newline: bool) -> Value {
    let data = args.first().map(|v| v.to_string_val()).unwrap_or_default();
    SOCKETS.with(|s| {
        let mut sockets = s.borrow_mut();
        if let Some(state) = sockets.get_mut(name) {
            let result = if newline {
                writeln!(state.stream, "{}", data)
            } else {
                write!(state.stream, "{}", data)
            };
            let _ = state.stream.flush();
            match result {
                Ok(()) => v_int(1),
                Err(_) => v_int(0),
            }
        } else {
            v_int(0)
        }
    })
}

fn socket_read(name: &str, args: &[Value]) -> Value {
    let max_bytes = args.first().map(|v| v.to_i64()).unwrap_or(4096) as usize;
    SOCKETS.with(|s| {
        let mut sockets = s.borrow_mut();
        if let Some(state) = sockets.get_mut(name) {
            let mut buf = vec![0u8; max_bytes];
            match state.stream.read(&mut buf) {
                Ok(n) => v_str(&String::from_utf8_lossy(&buf[..n])),
                Err(_) => v_str(""),
            }
        } else {
            v_str("")
        }
    })
}

fn socket_readline(name: &str) -> Value {
    SOCKETS.with(|s| {
        let mut sockets = s.borrow_mut();
        if let Some(state) = sockets.get_mut(name) {
            let mut line = String::new();
            match state.reader.read_line(&mut line) {
                Ok(0) => v_str(""),
                Ok(_) => v_str(line.trim_end_matches('\n').trim_end_matches('\r')),
                Err(_) => v_str(""),
            }
        } else {
            v_str("")
        }
    })
}

// ---------------------------------------------------------------------------
// RServerSocket (TCP server) — channel-based event polling
// ---------------------------------------------------------------------------

/// Events generated by the server background threads
enum ServerEvent {
    ClientConnect { addr: String, stream_id: usize },
    DataReceived { stream_id: usize, addr: String, data: String },
    ClientDisconnect { addr: String, stream_id: usize },
}

struct ServerState {
    /// Shared client list that background threads can write to and broadcast to
    clients: Arc<Mutex<Vec<(usize, TcpStream, String)>>>,
    /// Receiver for events from background threads
    events: mpsc::Receiver<ServerEvent>,
    /// Flag to signal shutdown
    running: Arc<Mutex<bool>>,
    /// Next client id
    next_id: Arc<Mutex<usize>>,
}

thread_local! {
    static SERVERS: RefCell<HashMap<String, ServerState>> = RefCell::new(HashMap::new());
}

pub fn server_socket_method(name: &str, method: &str, args: &[Value]) -> Value {
    let name_lower = name.to_lowercase();
    match method {
        "start" | "listen" => server_start(&name_lower),
        "stop" => server_stop(&name_lower),
        "broadcast" => server_broadcast(&name_lower, args),
        "accept" => server_accept(&name_lower),
        "poll" => server_poll(&name_lower),
        "sendto" => server_sendto(&name_lower, args),
        _ => {
            eprintln!("[WARN] RServerSocket.{}() not implemented", method);
            v_null()
        }
    }
}

fn server_start(name: &str) -> Value {
    let host = crate::object::rp_comp_get(name, "host").to_string_val();
    let port = crate::object::rp_comp_get(name, "port").to_i64() as u16;
    let addr = format!("{}:{}", host, port);

    let listener = match TcpListener::bind(&addr) {
        Ok(l) => l,
        Err(e) => {
            eprintln!("[ServerSocket] Bind error: {}", e);
            return v_int(0);
        }
    };
    let _ = listener.set_nonblocking(true);

    let (tx, rx) = mpsc::channel::<ServerEvent>();
    let running = Arc::new(Mutex::new(true));
    let clients: Arc<Mutex<Vec<(usize, TcpStream, String)>>> = Arc::new(Mutex::new(Vec::new()));
    let next_id = Arc::new(Mutex::new(1usize));

    // Spawn accept thread
    let accept_running = Arc::clone(&running);
    let accept_clients = Arc::clone(&clients);
    let accept_tx = tx.clone();
    let accept_next_id = Arc::clone(&next_id);

    std::thread::spawn(move || {
        while *accept_running.lock().unwrap() {
            match listener.accept() {
                Ok((stream, addr)) => {
                    let addr_str = addr.to_string();
                    let _ = stream.set_read_timeout(Some(Duration::from_millis(100)));
                    let _ = stream.set_nonblocking(false);

                    let mut id_lock = accept_next_id.lock().unwrap();
                    let client_id = *id_lock;
                    *id_lock += 1;
                    drop(id_lock);

                    // Clone stream for reading thread
                    let read_stream = match stream.try_clone() {
                        Ok(s) => s,
                        Err(_) => continue,
                    };

                    // Store in shared clients list
                    accept_clients.lock().unwrap().push(
                        (client_id, stream, addr_str.clone())
                    );

                    let _ = accept_tx.send(ServerEvent::ClientConnect {
                        addr: addr_str.clone(),
                        stream_id: client_id,
                    });

                    // Spawn per-client reader thread
                    let reader_tx = accept_tx.clone();
                    let reader_running = Arc::clone(&accept_running);
                    let reader_clients = Arc::clone(&accept_clients);
                    std::thread::spawn(move || {
                        let mut reader = BufReader::new(read_stream);
                        loop {
                            if !*reader_running.lock().unwrap() { break; }
                            let mut line = String::new();
                            match reader.read_line(&mut line) {
                                Ok(0) => {
                                    // Connection closed
                                    let _ = reader_tx.send(ServerEvent::ClientDisconnect {
                                        addr: addr_str.clone(),
                                        stream_id: client_id,
                                    });
                                    reader_clients.lock().unwrap().retain(|(id, _, _)| *id != client_id);
                                    break;
                                }
                                Ok(_) => {
                                    let trimmed = line.trim().to_string();
                                    if !trimmed.is_empty() {
                                        let _ = reader_tx.send(ServerEvent::DataReceived {
                                            stream_id: client_id,
                                            addr: addr_str.clone(),
                                            data: trimmed,
                                        });
                                    }
                                }
                                Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock
                                    || e.kind() == std::io::ErrorKind::TimedOut => {
                                    // No data available yet — just loop
                                    std::thread::sleep(Duration::from_millis(10));
                                }
                                Err(_) => {
                                    let _ = reader_tx.send(ServerEvent::ClientDisconnect {
                                        addr: addr_str.clone(),
                                        stream_id: client_id,
                                    });
                                    reader_clients.lock().unwrap().retain(|(id, _, _)| *id != client_id);
                                    break;
                                }
                            }
                        }
                    });
                }
                Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                    std::thread::sleep(Duration::from_millis(50));
                }
                Err(_) => {
                    std::thread::sleep(Duration::from_millis(50));
                }
            }
        }
    });

    SERVERS.with(|s| {
        s.borrow_mut().insert(
            name.to_string(),
            ServerState {
                clients,
                events: rx,
                running,
                next_id,
            },
        );
    });

    // Start automatic polling thread that fires events on the main thread via stdout messages
    // For console apps, we auto-poll by launching a helper thread that prints events
    let name_owned = name.to_string();
    start_auto_poll(&name_owned);

    v_int(1)
}

/// Auto-poll: drain channel events and fire them on the main thread.
/// For console-mode servers, start a polling thread that uses channels.
fn start_auto_poll(name: &str) {
    // For now, events will be fired when server.poll() is called explicitly,
    // or from the accept/read threads directly via println.
    // The chat example will be updated to use a poll loop.
    let _ = name;
}

/// Drain pending events and fire handlers on the calling thread.
fn server_poll(name: &str) -> Value {
    let mut events_to_fire: Vec<ServerEvent> = Vec::new();
    SERVERS.with(|s| {
        let servers = s.borrow();
        if let Some(state) = servers.get(name) {
            // Non-blocking drain
            while let Ok(evt) = state.events.try_recv() {
                events_to_fire.push(evt);
            }
            // Update client count
            let count = state.clients.lock().unwrap().len() as i64;
            rp_comp_set(name, "clientcount", v_int(count));
        }
    });

    for evt in events_to_fire {
        match evt {
            ServerEvent::ClientConnect { addr, .. } => {
                rp_fire_event_1(name, "onclientconnect", v_str(&addr));
            }
            ServerEvent::DataReceived { addr, data, .. } => {
                rp_fire_event_2(name, "ondatareceived", v_str(&addr), v_str(&data));
            }
            ServerEvent::ClientDisconnect { addr, .. } => {
                rp_fire_event_1(name, "onclientdisconnect", v_str(&addr));
            }
        }
    }
    v_null()
}

fn server_stop(name: &str) -> Value {
    SERVERS.with(|s| {
        if let Some(state) = s.borrow_mut().remove(name) {
            *state.running.lock().unwrap() = false;
        }
    });
    v_null()
}

fn server_broadcast(name: &str, args: &[Value]) -> Value {
    let data = args.first().map(|v| v.to_string_val()).unwrap_or_default();
    SERVERS.with(|s| {
        let servers = s.borrow();
        if let Some(state) = servers.get(name) {
            let mut clients = state.clients.lock().unwrap();
            clients.retain_mut(|(_, stream, _)| {
                writeln!(stream, "{}", data).is_ok()
            });
        }
    });
    v_null()
}

/// Send data to a specific client by index (0-based) or address.
fn server_sendto(name: &str, args: &[Value]) -> Value {
    let target = args.first().map(|v| v.to_string_val()).unwrap_or_default();
    let data = args.get(1).map(|v| v.to_string_val()).unwrap_or_default();
    SERVERS.with(|s| {
        let servers = s.borrow();
        if let Some(state) = servers.get(name) {
            let mut clients = state.clients.lock().unwrap();
            for (_, stream, addr) in clients.iter_mut() {
                if addr == &target {
                    let _ = writeln!(stream, "{}", data);
                    break;
                }
            }
        }
    });
    v_null()
}

fn server_accept(name: &str) -> Value {
    // Legacy manual accept - just poll for events
    server_poll(name)
}

// ---------------------------------------------------------------------------
// RHTTP (HTTP client using ureq)
// ---------------------------------------------------------------------------

pub fn http_method(name: &str, method: &str, args: &[Value]) -> Value {
    let name_lower = name.to_lowercase();
    match method {
        "get" => http_get(&name_lower, args),
        "post" => http_post(&name_lower, args),
        _ => {
            eprintln!("[WARN] RHTTP.{}() not implemented", method);
            v_null()
        }
    }
}

fn http_get(name: &str, args: &[Value]) -> Value {
    let url = args.first().map(|v| v.to_string_val()).unwrap_or_default();
    let timeout_ms = crate::object::rp_comp_get(name, "timeout").to_i64().max(1000) as u64;

    let agent = ureq::AgentBuilder::new()
        .timeout(Duration::from_millis(timeout_ms))
        .build();

    match agent.get(&url).call() {
        Ok(response) => {
            let status = response.status();
            let body = response.into_string().unwrap_or_default();
            rp_comp_set(name, "statuscode", v_int(status as i64));
            rp_comp_set(name, "responsetext", v_str(&body));
            rp_comp_set(name, "url", v_str(&url));
            v_str(&body)
        }
        Err(e) => {
            eprintln!("[HTTP] GET error: {}", e);
            rp_comp_set(name, "statuscode", v_int(0));
            rp_comp_set(name, "responsetext", v_str(""));
            v_str("")
        }
    }
}

fn http_post(name: &str, args: &[Value]) -> Value {
    let url = args.first().map(|v| v.to_string_val()).unwrap_or_default();
    let body = args.get(1).map(|v| v.to_string_val()).unwrap_or_default();
    let timeout_ms = crate::object::rp_comp_get(name, "timeout").to_i64().max(1000) as u64;

    let agent = ureq::AgentBuilder::new()
        .timeout(Duration::from_millis(timeout_ms))
        .build();

    match agent
        .post(&url)
        .set("Content-Type", "application/x-www-form-urlencoded")
        .send_string(&body)
    {
        Ok(response) => {
            let status = response.status();
            let resp_body = response.into_string().unwrap_or_default();
            rp_comp_set(name, "statuscode", v_int(status as i64));
            rp_comp_set(name, "responsetext", v_str(&resp_body));
            rp_comp_set(name, "url", v_str(&url));
            v_str(&resp_body)
        }
        Err(e) => {
            eprintln!("[HTTP] POST error: {}", e);
            rp_comp_set(name, "statuscode", v_int(0));
            rp_comp_set(name, "responsetext", v_str(""));
            v_str("")
        }
    }
}
