' VARPTR, MEMCPY, MEMSET, MEMCMP, VARPTR$, SIZEOF, RTLMOVEMEMORY, a
' stream's Pointer, WriteUDT / ReadUDT (manual examples): memory-safe,
' RapidQ's byte layout, the same on every backend
TYPE TTest
  S AS STRING * 8
  N AS INTEGER
  D AS DOUBLE
END TYPE

DEFINT I = 90, J = 10
MEMCPY(VARPTR(I), VARPTR(J), SIZEOF(INTEGER))
PRINT "I ="; I
PRINT SIZEOF(BYTE); SIZEOF(SHORT); SIZEOF(INTEGER); SIZEOF(LONG); SIZEOF(SINGLE); SIZEOF(DOUBLE); SIZEOF(TTest)

DIM sTest AS STRING
sTest = "This is a test string"
PRINT VARPTR$(VARPTR(sTest))
PRINT VARPTR$(VARPTR(sTest) + 5)
MEMCPY VARPTR(sTest), VARPTR("THIS"), 4
PRINT sTest; LEN(sTest)

DIM A(0 TO 5) AS INTEGER
FOR k = 0 TO 5: A(k) = k * 10: NEXT
MEMSET(VARPTR(A(1)), 0, 2 * SIZEOF(INTEGER))
MEMCPY VARPTR(A(4)), VARPTR(A(0)) + 4 * 3, SIZEOF(INTEGER)
FOR k = 0 TO 5: PRINT A(k);: NEXT: PRINT

DIM B(1 TO 4) AS BYTE
B(1) = 1: B(2) = 2: B(3) = 3: B(4) = 4
DIM L AS LONG
MEMCPY VARPTR(L), VARPTR(B(1)), 4
PRINT HEX$(L)

DIM T1 AS TTest, T2 AS TTest
T1.S = "qwerty": T1.N = 12345: T1.D = 2.5
MEMCPY T2, T1, SIZEOF(T1)
PRINT T2.S; T2.N; T2.D; MEMCMP(T1, T2, SIZEOF(T1))
T2.N = 1
PRINT MEMCMP(T1, T2, SIZEOF(T1))
MEMSET T2, 0, SIZEOF(T2)
PRINT "["; T2.S; "]"; T2.N; T2.D

DIM X AS DOUBLE, Y AS DOUBLE
Y = 3.25
RTLMOVEMEMORY X, Y, SIZEOF(DOUBLE)
PRINT X

DIM Mem AS QMEMORYSTREAM
Mem.WriteUDT(T1)
PRINT Mem.Size
Mem.Position = 0
DIM T3 AS TTest
Mem.ReadUDT(T3)
PRINT T3.S; T3.N; T3.D
DIM N AS INTEGER
MEMCPY VARPTR(N), Mem.Pointer + 8, 4
PRINT N

SUB Swap4 (p1 AS LONG, p2 AS LONG)
  DIM t AS LONG
  MEMCPY VARPTR(t), p1, 4
  MEMCPY p1, p2, 4
  MEMCPY p2, VARPTR(t), 4
END SUB
DIM P AS INTEGER, Q AS INTEGER
P = 1: Q = 2
Swap4 VARPTR(P), VARPTR(Q)
PRINT P; Q
