[package]
name = "rapidr-codegen-rust"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true

[dependencies]
rapidr-ast.workspace = true
# (the DECLARE … LIB calling spec: rapidr_value::dll)
rapidr-value = { workspace = true }
rapidr-diagnostics.workspace = true
rapidr-parser.workspace = true

[dev-dependencies]
rapidr-lexer.workspace = true
