[package]
name = "rapidr-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
rapidr-codegen-rust.workspace = true
rapidr-lexer.workspace = true
rapidr-parser.workspace = true
rapidr-preprocessor.workspace = true

[[bin]]
name = "rapidr"
path = "src/main.rs"