#!/usr/bin/env python3
"""The icons in context, drawn by the UI kernel (dev tool): writes
design/icons/mockups/studio.rr — a RapidR program with a toolbar row of
flat QCOOLBTNs, a toolbox column and a problems / breakpoints list (both
QTREEVIEWs), its icons loaded through the public API (Bitmap.LoadIcon,
ImageList.AddIcon) — builds it interpreted with the workspace's CLI, runs
it headless in each theme at 1x and 2x (RAPIDR_CAPTURE, RAPIDR_THEME,
RAPIDR_SCALE) and writes design/icons/review/mockup-<theme>-<scale>x.png.

    python3 design/icons/tools/mockups.py [--rapidr target/release/rapidr] [--themes …] [--scales 1,2]

Needs `sips` (macOS) or Pillow to turn the captures into PNG.
"""

import argparse
import os
import subprocess
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ICONS = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(ICONS))

TOOLBAR = [
    ["new-file", "open", "save", "save-all"],
    ["undo", "redo"],
    ["cut", "copy", "paste", "find", "replace"],
    ["run", "pause", "stop", "debug", "build"],
    ["step-over", "step-into", "step-out", "run-to-cursor", "breakpoint"],
    ["align-left", "align-center", "align-top", "distribute-horizontal", "same-size", "bring-to-front"],
    ["dock", "split-vertical", "settings", "ai"],
]

TOOLBOX = [
    ("Standard", "groups/standard", "QFORM QBUTTON QLABEL QEDIT QCHECKBOX QRADIOBUTTON QCOMBOBOX QLISTBOX QIMAGE QTIMER"),
    ("Additional", "groups/additional", "QTABCONTROL QSTRINGGRID QTREEVIEW QLISTVIEW QTRACKBAR QGAUGE"),
    ("Dialogs", "groups/dialogs", "QOPENDIALOG QSAVEDIALOG QCOLORDIALOG"),
    ("Controls (RapidR)", "groups/controls", "RMEMO RUPDOWN RDATETIMEPICKER RTOOLBAR"),
    ("Data", "groups/data", "RSQLITE RDBQUERY RDBGRID RDATASOURCE"),
    ("Data Science", "groups/datascience", "RDATAFRAME RPLOT RDFFILTER RDFGROUP"),
    ("Web", "groups/web", "RWEBVIEW RHTTP"),
]

PROBLEMS = [
    ("error", "Undeclared variable Total (Main.rr, line 12)"),
    ("warning", "QPLOT is RapidR's: not in a RapidQ-compatible project"),
    ("info", "Form1 has 14 components"),
    ("hint", "Use a CONST for 3.14159"),
    ("breakpoint", "Main.rr, line 20"),
    ("breakpoint-conditional", "Main.rr, line 31: Count > 10"),
    ("logpoint", "Main.rr, line 44: log Total"),
    ("breakpoint-disabled", "Forms.inc, line 8"),
    ("breakpoint-hit", "Main.rr, line 52 (stopped here)"),
    ("execution-point", "Main.rr, line 53 (next statement)"),
]


def program():
    L = ["' Generated by design/icons/tools/mockups.py: RapidR's icons in context,",
         "' drawn by the UI kernel through the public API (Bitmap.LoadIcon, ImageList.AddIcon).",
         "DIM Pics AS QIMAGELIST",
         "Pics.Width = 16 : Pics.Height = 16",
         "DIM Marks AS QIMAGELIST",
         "Marks.Width = 16 : Marks.Height = 16",
         "",
         'CREATE Form AS QFORM',
         '  Caption = "RapidR Studio: icons in context"',
         "  Width = 900 : Height = 560",
         "  CREATE Bar AS QPANEL",
         "    Left = 0 : Top = 0 : Width = 892 : Height = 34",
         "    BevelOuter = 0",
         "  END CREATE"]
    x = 6
    n = 0
    for group in TOOLBAR:
        for name in group:
            n += 1
            L += [f"  CREATE T{n} AS QCOOLBTN",
                  f"    Parent = Bar : Left = {x} : Top = 5 : Width = 24 : Height = 24 : Flat = 1",
                  f'    Hint = "{name}"',
                  "  END CREATE"]
            x += 26
        x += 10
    L += ["  CREATE Box AS QTREEVIEW",
          "    Left = 6 : Top = 40 : Width = 230 : Height = 476",
          "    Images = Pics",
          "  END CREATE",
          "  CREATE Problems AS QTREEVIEW",
          "    Left = 244 : Top = 40 : Width = 640 : Height = 220",
          "    Images = Marks : ShowLines = 0 : ShowRoot = 0",
          "  END CREATE",
          "END CREATE",
          ""]
    n = 0
    for group in TOOLBAR:
        for name in group:
            n += 1
            L.append(f'DIM G{n} AS QBITMAP : G{n}.LoadIcon "{name}", 16 : T{n}.BMPHandle = G{n}')
    L.append("")
    node = 0
    image = 0
    for title, gicon, members in TOOLBOX:
        root = node
        L += [f'Box.AddItems "{title}"', f'Pics.AddIcon "{gicon}"',
              f"Box.Item({node}).ImageIndex = {image} : Box.Item({node}).SelectedIndex = {image}"]
        node += 1
        image += 1
        for t in members.split():
            L += [f'Box.AddChildItems {root}, "{t}"', f'Pics.AddIcon "{t}"',
                  f"Box.Item({node}).ImageIndex = {image} : Box.Item({node}).SelectedIndex = {image}"]
            node += 1
            image += 1
    L.append("Box.FullExpand")
    L.append("")
    for i, (mark, text) in enumerate(PROBLEMS):
        L += [f'Problems.AddItems "{text}"', f'Marks.AddIcon "{mark}"',
              f"Problems.Item({i}).ImageIndex = {i} : Problems.Item({i}).SelectedIndex = {i}"]
    L += ["", "Form.ShowModal", ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rapidr", default=os.path.join(ROOT, "target", "release", "rapidr"))
    ap.add_argument("--themes", default="classic,modern,dark,highcontrast")
    ap.add_argument("--scales", default="1,2")
    a = ap.parse_args()
    src = os.path.join(ICONS, "mockups", "studio.rr")
    os.makedirs(os.path.dirname(src), exist_ok=True)
    open(src, "w").write(program())
    work = tempfile.mkdtemp(prefix="rapidr-icons-mockup-")
    subprocess.run([a.rapidr, "build", src, work, "--interp"], check=True, stdout=subprocess.DEVNULL)
    exe = os.path.join(work, "studio")
    out_dir = os.path.join(ICONS, "review")
    os.makedirs(out_dir, exist_ok=True)
    for theme in a.themes.split(","):
        for scale in a.scales.split(","):
            cap = os.path.join(work, f"cap-{theme}-{scale}")
            env = dict(os.environ, RAPIDR_THEME=theme, RAPIDR_SCALE=scale, RAPIDR_CAPTURE=cap,
                       RAPIDR_PRINT_TO=os.path.join(work, "prints"), RAPIDR_REGISTRY=os.path.join(work, "r.reg"))
            subprocess.run([exe], env=env, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=120)
            png = os.path.join(out_dir, f"mockup-{theme}-{scale}x.png")
            try:
                from PIL import Image
                Image.open(cap + "-1.bmp").save(png)
            except ImportError:
                subprocess.run(["sips", "-s", "format", "png", cap + "-1.bmp", "--out", png], check=True, stdout=subprocess.DEVNULL)
            print(os.path.relpath(png, ROOT))


if __name__ == "__main__":
    main()
