#!/usr/bin/env python3
"""Generate the user manual's reference pages from the source of truth.

    python3 tools/manual_reference.py           write docs/manual/reference/*.md
    python3 tools/manual_reference.py --check   exit 1 if they are out of date

What it reads (nothing is copied by hand):

- components.md: `COMPONENT_TYPES` in crates/rapidr-ast/src/lib.rs (every
  component both compilers create), the RapidQ-name rules of
  `canonical_type_name` (QGAUGE, QOUTLINE, COMPORT), `LIBRARY_TYPES`
  (crates/rapidr-ast/src/library.rs), `INCLUDE_LIBRARY_COMPONENTS`,
  `RAPIDQ_OBJECTS_NOT_YET_IMPLEMENTED` and the preprocessor's
  `RAPIDR_LIBRARIES` (QDIRLISTVIEW, QDOCKFORM);
- builtins.md: `BUILTINS` and `BARE_BUILTINS` in
  interpreter/rapidr-bytecode/src/builtins.rs (the list every runtime's
  dispatch is unit-tested against);
- data-science.md: the `match` arms of RNUM / RDATAFRAME / RPLOT's methods
  and properties in crates/rapidr-runtime-core/src/datascience.rs (desktop:
  native and interpreted) and crates/rapidr-runtime-web/src/datascience_web.rs
  (the web).

The only hand-kept data here are the component categories and RapidQ's own
component list (RC.EXE's built-in names, plus the include libraries'), both
checked against COMPONENT_TYPES so that a new component can't go unlisted:
the script fails and names it.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "manual", "reference")

HEADER = "<!-- Generated by tools/manual_reference.py from {src}. Do not edit: change the source and run the script again. -->\n\n"


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return f.read()


def const_list(src, name):
    """The string literals of `pub const NAME: &[&str] = &[ … ];`."""
    m = re.search(r"pub const " + re.escape(name) + r"\s*:\s*&\[[^=]*=\s*&\[(.*?)\];", src, re.S)
    if not m:
        sys.exit(f"manual_reference: {name} not found")
    body = re.sub(r"//[^\n]*", "", m.group(1))
    return re.findall(r'"([^"]*)"', body)


def const_pairs(src, name):
    m = re.search(r"pub const " + re.escape(name) + r"\s*:[^=]*=\s*&\[(.*?)\];", src, re.S)
    if not m:
        sys.exit(f"manual_reference: {name} not found")
    return re.findall(r'\(\s*"([^"]*)"\s*,\s*"([^"]*)"', m.group(1))


# --- Components -------------------------------------------------------------

# RapidQ's built-in components: the names RapidQ's compiler (RC.EXE, Rapid-Q
# 2006) knows (docs/rapidq-ground-truth.md). QCOMPORT is RC.EXE's too.
RAPIDQ_BUILTIN = """QBITMAP QBUTTON QCANVAS QCHECKBOX QCOMBOBOX QCOMPORT QCOOLBTN QD3DFACE
QD3DFRAME QD3DLIGHT QD3DMESH QD3DMESHBUILDER QD3DTEXTURE QD3DVECTOR QD3DVISUAL QD3DWRAP
QDIRTREE QDXIMAGELIST QDXJOYSTICK QDXSCREEN QDXSOUND QDXTIMER QEDIT QFILELISTBOX
QFILESTREAM QFONT QFONTDIALOG QFORM QGAUGE QGLASSFRAME QGROUPBOX QHEADER QIMAGE
QIMAGELIST QLABEL QLISTBOX QLISTVIEW QMAINMENU QMEMORYSTREAM QMENUITEM QMYSQL
QNOTIFYICONDATA QOLECONTAINER QOLEOBJECT QOPENDIALOG QOUTLINE QOVALBTN QPANEL
QPOPUPMENU QPRINTER QRADIOBUTTON QRECT QREGISTRY QRICHEDIT QSAVEDIALOG QSCROLLBAR QSCROLLBOX
QSOCKET QSPLITTER QSTATUSBAR QSTRINGGRID QSTRINGLIST QTABCONTROL QTIMER QTRACKBAR
QTREEVIEW""".split()

# Components RapidQ programs get from RapidQ's include libraries (RapidR
# builds them in): the name and the library.
RAPIDQ_LIBRARY = {
    "QFORMMDI": "RAPIDQ2.INC",
    "QFILEDIALOG": "RAPIDQ2.INC",
    "QCOLORDIALOG": "RAPIDQ2.INC",
    "QBEVEL": "QBevel.inc",
    "QDIGDISPLAY": "QDigDisplay.inc",
    "QCGI": "qcgi.inc",
    "QDOWNLOAD": "Qdownload.inc",
    "QMIDI": "QMidi.inc",
    "QWAVE": "QWave.inc",
    "QVIDEO": "QVideo.inc",
    "QCDAUDIO": "Qcdaudio.inc",
}

# What each component is for (the manual's grouping). Every COMPONENT_TYPES
# entry must be here.
CATEGORIES = [
    ("Forms and containers", "RFORM RFORMMDI RPANEL RGROUPBOX RTABCONTROL RSPLITTER RSCROLLBOX RBEVEL RGLASSFRAME RTOOLBAR RSTATUSBAR"),
    ("Buttons and input", "RBUTTON RCOOLBTN ROVALBTN RCHECKBOX RRADIOBUTTON REDIT RMEMO RRICHEDIT RCOMBOBOX RSCROLLBAR RTRACKBAR RUPDOWN RDATETIMEPICKER RCODEEDITOR"),
    ("Display and drawing", "RLABEL RIMAGE RCANVAS RPROGRESSBAR RPROGRESS RDIGDISPLAY RHEADER RDESIGNSURFACE"),
    ("Lists, grids and trees", "RLISTBOX RFILELISTBOX RDIRTREE RLISTVIEW RTREEVIEW RSTRINGGRID"),
    ("Menus", "RMAINMENU RMENUITEM RPOPUPMENU"),
    ("Dialogs", "ROPENDIALOG RSAVEDIALOG RFILEDIALOG RCOLORDIALOG RFONTDIALOG"),
    ("Non-visual objects", "RTIMER RFONT RBITMAP RIMAGELIST RSTRINGLIST RFILESTREAM RMEMORYSTREAM RREGISTRY RPRINTER RRECT RNOTIFYICONDATA RJSON"),
    ("Databases", "RSQLITE RMYSQL"),
    ("Network, devices and CGI", "RSOCKET RSERVERSOCKET RHTTP RDOWNLOAD RCOMPORT RCGI"),
    ("Media", "RMIDI RWAVE RVIDEO RCDAUDIO"),
    ("DirectX 2D", "RDXSCREEN RDXIMAGELIST RDXTIMER RDXSOUND RDXJOYSTICK"),
    ("Direct3D (retained mode)", "RD3DFRAME RD3DMESHBUILDER RD3DMESH RD3DFACE RD3DLIGHT RD3DTEXTURE RD3DVISUAL RD3DWRAP RD3DVECTOR"),
    ("Data science", "RNUM RDATAFRAME RPLOT"),
    ("Web only", "RWEBVIEW RDOM RJAVASCRIPT RWEBSTORAGE RWEBAUDIO RWEBVIDEO RWEBNOTIFICATION RWEBGEOLOCATION RROUTER"),
]

# Where a component works when it isn't everywhere (desktop = native and
# interpreted builds). Checked in the runtimes: RMYSQL and RSERVERSOCKET
# need raw TCP (crates/rapidr-runtime-web/src/database_web.rs warns), the
# web components are the browser's.
WHERE = {
    "RMYSQL": "desktop",
    "RSERVERSOCKET": "desktop",
    "RSOCKET": "desktop (TCP); web (WebSocket)",
    "RCOMPORT": "desktop (serial2); web (Web Serial)",
}


def q_names(r, lib_types, include_lib):
    """The RapidQ names that mean component `r` (canonical_type_name's
    rules, reversed), with where each comes from."""
    names = []
    rest = r[1:]
    q = "Q" + rest
    if q in RAPIDQ_BUILTIN:
        names.append((q, "RapidQ"))
    elif q in RAPIDQ_LIBRARY:
        names.append((q, RAPIDQ_LIBRARY[q]))
    for qq, rr in include_lib:
        if rr == r and qq not in [n for n, _ in names]:
            names.append((qq, RAPIDQ_LIBRARY.get(qq, "include library")))
    if r == "RPROGRESSBAR":
        names.append(("QGAUGE", "RapidQ"))
    if r == "RTREEVIEW":
        names.append(("QOUTLINE", "RapidQ"))
    for t, rr in lib_types:
        if rr == r and not t.startswith("Q"):
            names.append((t, "RAPIDQ2.INC"))
    return names


def components():
    ast = read("crates/rapidr-ast/src/lib.rs")
    types = const_list(ast, "COMPONENT_TYPES")
    not_yet = const_list(ast, "RAPIDQ_OBJECTS_NOT_YET_IMPLEMENTED")
    include_lib = const_pairs(ast, "INCLUDE_LIBRARY_COMPONENTS")
    lib_types = const_pairs(read("crates/rapidr-ast/src/library.rs"), "LIBRARY_TYPES")
    pre = read("crates/rapidr-preprocessor/src/lib.rs")
    rapidr_libs = re.findall(r'\(\s*"([A-Z]+)"\s*,\s*"([^"]+\.inc)"', pre)

    categorized = [t for _, ts in CATEGORIES for t in ts.split()]
    missing = [t for t in types if t not in categorized]
    extra = [t for t in categorized if t not in types]
    if missing or extra:
        sys.exit(f"manual_reference: update CATEGORIES (not categorized: {missing}; not components: {extra})")
    for q in RAPIDQ_BUILTIN + list(RAPIDQ_LIBRARY):
        r = {"QGAUGE": "RPROGRESSBAR", "QOUTLINE": "RTREEVIEW"}.get(q, "R" + q[1:])
        if r not in types and q not in not_yet:
            sys.exit(f"manual_reference: RapidQ's {q} has no component ({r}) and isn't in RAPIDQ_OBJECTS_NOT_YET_IMPLEMENTED")

    out = [HEADER.format(src="crates/rapidr-ast (COMPONENT_TYPES and the name rules) and crates/rapidr-preprocessor")]
    out.append("# Components: RapidQ's and RapidR's names\n\n")
    out.append(
        "Every component RapidR creates, by what it is for. A RapidQ name and its R name are the same "
        "component (same properties, methods, events and behaviour); a program may use either and mix them "
        "freely. A name with no RapidQ name is RapidR's own. Unless the last column says otherwise, a component "
        "works in native builds, interpreted programs and the browser.\n\n"
        "Members: RapidQ's components have the members RapidQ's documentation gives them, plus the additions "
        "listed in [Components and objects](../components.md#rapidrs-additions-to-every-component). RapidR's own "
        "components are described in the chapters on [databases](../databases.md), [data science](../data-science.md), "
        "[the web](../web.md) and [DirectX and media](../directx-and-media.md); the data-science members are listed "
        "in [data-science.md](data-science.md).\n\n"
    )
    total = 0
    rq = 0
    for title, ts in CATEGORIES:
        out.append(f"## {title}\n\n| RapidR name | RapidQ name | From | Where |\n|---|---|---|---|\n")
        for r in ts.split():
            names = q_names(r, lib_types, include_lib)
            total += 1
            rq += 1 if names else 0
            qn = ", ".join(f"`{n}`" for n, _ in names) or "—"
            src = ", ".join(sorted({s for _, s in names})) or "RapidR"
            out.append(f"| `{r}` | {qn} | {src} | {WHERE.get(r, 'everywhere' if title != 'Web only' else 'web')} |\n")
        out.append("\n")
    out.append("## RapidQ's include libraries built in\n\n")
    out.append("A program that names these (or includes the library) gets RapidR's own implementation, written in BASIC on RapidR's components, on every runtime:\n\n")
    for name, file in rapidr_libs:
        out.append(f"- `{name}` (RapidQ's `{file}`)\n")
    out.append("\n## Not implemented\n\n")
    out.append("These RapidQ objects compile (variables of their type are generic objects) but do nothing yet; calling their methods prints a warning:\n\n")
    for n in not_yet:
        out.append(f"- `{n}`\n")
    out.append(f"\n{total} components; {rq} of them have a RapidQ name.\n")
    return "".join(out)


# --- Builtins ---------------------------------------------------------------

# Names in BUILTINS that are the compilers' own lowerings of statements or of
# other spellings, not names a program writes.
INTERNAL = {"print", "println", "print_hash", "write_hash", "input_func", "input_field", "line_input",
            "date_func", "time_func", "rapidr__waitkey", "end", "e", "math.e", "math.pi", "get"}


def builtins():
    src = read("interpreter/rapidr-bytecode/src/builtins.rs")
    names = const_list(src, "BUILTINS")
    bare = set(const_list(src, "BARE_BUILTINS"))
    shown = sorted({n for n in names if not n.startswith("__") and n not in INTERNAL})
    out = [HEADER.format(src="interpreter/rapidr-bytecode/src/builtins.rs (BUILTINS, BARE_BUILTINS)")]
    out.append("# Built-in functions and statements\n\n")
    out.append(
        "The builtins every runtime implements (native builds, the interpreter and the web share one list, "
        "unit-tested against each runtime's dispatch). Names are not case-sensitive, and a builtin may be written "
        "with or without its type suffix: `MID$`, `Mid` and `mid` are the same. What each does is RapidQ's "
        "behaviour (see [the language](../language.md) for the rules that differ from other BASICs). "
        "Statements the compilers handle themselves (`DIM`, `INC`, `DEC`, `SWAP`, `REDIM`, `DATA` / `READ` / "
        "`RESTORE`, `BIND`, `CALLFUNC`, `CODEPTR`, `VARPTR`, `SIZEOF`, `QUICKSORT`, `INPUT`, `LINE INPUT`, "
        "`PRINT`, `WRITE`, `END`, …) are described in the language chapter.\n\n"
        "Marked *bare*: may be written without parentheses or arguments (`t = TIMER`).\n\n"
    )
    by_letter = {}
    for n in shown:
        by_letter.setdefault(n[0].upper(), []).append(n)
    out.append("| | Builtins |\n|---|---|\n")
    for letter in sorted(by_letter):
        cells = ", ".join(f"`{n.upper()}`" + (" *(bare)*" if n in bare else "") for n in by_letter[letter])
        out.append(f"| {letter} | {cells} |\n")
    out.append(f"\n{len(shown)} names.\n")
    return "".join(out)


# --- Data science -----------------------------------------------------------

def arms(src, fn):
    """The string patterns of `fn`'s top-level match arms, with the `// ---
    Section ---` comments above them: [(section, [names])]."""
    m = re.search(r"pub fn " + re.escape(fn) + r"\s*\(", src)
    if not m:
        return None
    body = src[m.end():]
    # (this function only: up to the next item at the file's top level)
    end = re.search(r"\n(?:pub(?:\([a-z]+\))? )?fn |\n// -{10}", body)
    if end:
        body = body[: end.start()]
    # (the match on the method's or property's name, also as `Some(x) =>
    # match prop {`)
    mm = re.search(r"\n([ \t]*)(?:[^\n]*=> )?match (?:method|prop|lmethod|m) \{\n", body)
    if not mm:
        return None
    lines = body[mm.end():].split("\n")
    first = next((l for l in lines if l.strip()), "")
    indent = first[: len(first) - len(first.lstrip())]
    result = []
    section = ""
    for line in lines:
        if line.strip() and not line.startswith(indent):
            break
        if not line.startswith(indent) or line.startswith(indent + " "):
            continue
        t = line[len(indent):]
        sec = re.match(r"//\s*-+\s*(.*?)\s*-+\s*$", t)
        if sec:
            section = sec.group(1)
            continue
        am = re.match(r'((?:"[^"]+"\s*\|\s*)*"[^"]+")\s*(?:if [^=]*)?=>', t)
        if am:
            result.append((section, re.findall(r'"([^"]+)"', am.group(1))))
    return result


def data_science():
    core = read("crates/rapidr-runtime-core/src/datascience.rs")
    web = read("crates/rapidr-runtime-web/src/datascience_web.rs")
    out = [HEADER.format(src="crates/rapidr-runtime-core/src/datascience.rs and crates/rapidr-runtime-web/src/datascience_web.rs")]
    out.append("# Data-science members: RNUM, RDATAFRAME, RPLOT\n\n")
    out.append(
        "Every method and property name the runtimes answer, with its aliases. *Desktop* is native builds and "
        "interpreted programs (one implementation: ndarray, polars, plotters); *web* is the browser's runtime. "
        "Names are not case-sensitive, and a method that returns a value can be read like a property on every "
        "runtime (`PRINT arr.Sum`). The desktop and the web are two implementations today; where a row has a "
        "dash, that runtime doesn't answer the name. How to use them: [Data science](../data-science.md).\n\n"
    )
    for obj, fns in [
        ("RNUM", [("Methods", "num_method"), ("Properties (read)", "num_get_prop"), ("Properties (set)", "num_set_prop")]),
        ("RDATAFRAME", [("Methods", "dataframe_method"), ("Properties (read)", "dataframe_get_prop")]),
        ("RPLOT", [("Methods", "plot_method"), ("Properties (read)", "plot_get_prop"), ("Properties (set)", "plot_set_prop")]),
    ]:
        out.append(f"## {obj}\n\n")
        for title, fn in fns:
            d = arms(core, fn) or []
            w = arms(web, fn) or []
            web_names = {n for _, ns in w for n in ns}
            desk_names = {n for _, ns in d for n in ns}
            out.append(f"### {title}\n\n| Name (aliases) | Group | Desktop | Web |\n|---|---|:-:|:-:|\n")
            seen = set()
            for section, ns in d:
                key = tuple(ns)
                if key in seen:
                    continue
                seen.add(key)
                on_web = "✓" if any(n in web_names for n in ns) else "—"
                out.append(f"| {', '.join(f'`{n}`' for n in ns)} | {section or ''} | ✓ | {on_web} |\n")
            for section, ns in w:
                if not any(n in desk_names for n in ns):
                    out.append(f"| {', '.join(f'`{n}`' for n in ns)} | {section or ''} | — | ✓ |\n")
            out.append("\n")
    return "".join(out)


def main():
    pages = {"components.md": components(), "builtins.md": builtins(), "data-science.md": data_science()}
    check = "--check" in sys.argv[1:]
    stale = []
    os.makedirs(OUT, exist_ok=True)
    for name, text in pages.items():
        path = os.path.join(OUT, name)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old == text:
            continue
        if check:
            stale.append(name)
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            print(f"wrote {os.path.relpath(path, ROOT)}")
    if stale:
        sys.exit(f"out of date: {', '.join(stale)} (python3 tools/manual_reference.py)")


if __name__ == "__main__":
    main()
