#!/usr/bin/env python3
"""Generate THIRD_PARTY_NOTICES.md: every open-source Rust library RapidR
ships (desktop binary, runtimes linked into built apps, the web IDE's wasm),
with its version, license and upstream link.

The list is computed from `cargo metadata`: all workspace crates and their
normal (non-dev) dependencies, transitively. Build-only and dev-only
dependencies are left out; they never reach users.

Usage (repo root):
    python3 tools/third_party_notices.py          # rewrite THIRD_PARTY_NOTICES.md
    python3 tools/third_party_notices.py --check  # fail if it's out of date (CI)

JavaScript/CSS vendored into the IDE (Monaco, …) is not a Cargo dependency;
it is credited by hand in LICENSES.md. The notices each *built program*
carries, with full licence texts, are another file: THIRD-PARTY-NOTICES.txt,
made per kind of output by `rapidr notices` (crates/rapidr-cli/src/notices.rs,
docs/licensing.md).
"""

import collections
import json
import os
import re
import subprocess
import sys
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "THIRD_PARTY_NOTICES.md")


def shipped_packages():
    meta = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--format-version", "1", "--locked"], cwd=ROOT))
    packages = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    members = set(meta["workspace_members"])
    seen, stack = set(), list(members)
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        for dep in nodes[pid]["deps"]:
            # kind None = normal dependency (compiled into what ships)
            if any(k.get("kind") is None for k in dep["dep_kinds"]):
                stack.append(dep["pkg"])
    # (a path package is RapidR's own: a member, or a crates.io crate's
    # replacement under crates/patches/, MIT like the rest of RapidR)
    return [packages[p] for p in seen - members if packages[p]["source"] is not None]


def clarifications():
    """License expressions `deny.toml` records for crates that ship only a
    license file (so this file and `cargo deny` agree)."""
    with open(os.path.join(ROOT, "deny.toml"), "rb") as f:
        deny = tomllib.load(f)
    return {c["crate"]: c["expression"] for c in deny.get("licenses", {}).get("clarify", [])}


def normalize(expr):
    """`MIT/Apache-2.0`, `Apache-2.0 OR MIT` → `Apache-2.0 OR MIT` (one
    spelling per set of alternatives); other expressions are kept."""
    expr = expr.replace(" / ", " OR ").replace("/", " OR ")
    if "(" in expr or " AND " in expr or " WITH " in expr:
        return expr
    return " OR ".join(sorted(t.strip() for t in re.split(r"\s+OR\s+", expr)))


def render(pkgs):
    clarified = clarifications()
    by_license = collections.defaultdict(list)
    for p in pkgs:
        lic = p.get("license") or clarified.get(p["name"]) or "UNKNOWN"
        by_license[normalize(lic)].append(p)
    lines = [
        "# Third-Party Notices",
        "",
        "RapidR is MIT-licensed (see [LICENSE](LICENSE)) and is built on the open-source",
        "Rust libraries below, which ship inside the `rapidr` binary, the runtimes linked",
        "into built apps, and the web IDE's WebAssembly. Thank you to all their authors.",
        "",
        "This file is generated by `python3 tools/third_party_notices.py` from the real",
        "dependency graph (CI fails if it is out of date). Licenses are checked against",
        "the permissive allowlist in `deny.toml`. JavaScript and other assets vendored",
        "into the IDE (e.g. the Monaco editor) are credited in [LICENSES.md](LICENSES.md),",
        "which also carries their full license texts. Every program RapidR builds carries",
        "its own `THIRD-PARTY-NOTICES.txt` with the full texts for what is inside it",
        "(`rapidr notices`; [LEGAL.md](LEGAL.md), [docs/licensing.md](docs/licensing.md)).",
        "",
        "The fonts RapidR draws text with are credited there too (§4). They are",
        "the Liberation fonts and the Noto fallback fonts (Noto Sans, Noto Sans",
        "Symbols and Symbols 2, Noto Sans SC and KR), all under the SIL Open Font",
        "License 1.1. The Noto fonts' chunks ship beside the web runtime with",
        "their `OFL.txt`.",
        "",
        f"**{len(pkgs)} libraries** under {len(by_license)} license expressions.",
        "",
    ]
    for lic in sorted(by_license, key=lambda l: (-len(by_license[l]), l)):
        group = sorted(by_license[lic], key=lambda p: (p["name"].lower(), p["version"]))
        lines += [f"## {lic} ({len(group)})", "", "| Library | Version | Upstream |", "|---|---|---|"]
        for p in group:
            url = p.get("repository") or p.get("homepage") or f"https://crates.io/crates/{p['name']}"
            lines.append(f"| {p['name']} | {p['version']} | <{url}> |")
        lines.append("")
    return "\n".join(lines)


def main():
    text = render(shipped_packages())
    unknown = "## UNKNOWN" in text
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("THIRD_PARTY_NOTICES.md is out of date: run python3 tools/third_party_notices.py")
            return 1
        print("THIRD_PARTY_NOTICES.md is up to date")
    else:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {OUT}")
    if unknown:
        print("error: some libraries declare no license; check them before shipping", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
